server:
  port: 9083
spring:
  application:
    name: provider-springcloud
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  datasource:
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    url: jdbc:mysql://127.0.0.1:3306/ehouse?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: YssB418531
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka/,http://localhost:9092/eureka/,http://localhost:9093/eureka/
feign:
  hystrix:
    enabled: true

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zhanglubin.providerspringcloud.provider.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mybatis/*Mapper.xml
